### ISSUE TITLE
Add non-interactive mode for `summoner`

### ISSUE THREAD

**Issue by willbasky** [kowainik/summoner#114]
I encountered such a problem. To test the changes in the template, I had create project each time and answer in interactive mode, although I knew the answers in advance.
Then I wrote down the answers in the `configuration.toml`, but some questions were still asked.

Is it possible to make `summoner` be quiet based on the configuration file?

**Comment by ChShersh** [comment]
@willbasky Could you tell what exact answers are asked?

**Comment by willbasky** [comment]
@ChShersh Fields in `conf.toml` are
```toml
cabal = true
stack = true

owner       = "willbasky"
description = "testAll"
fullName    = "willbasky"
email       = "email@gmail.com"
category    = "TestAll"
license     = "MIT"

github   = true
travis   = true
appveyor = false

lib      = true
exe      = true
test     = true
bench    = true

bscript  = false
private  = false
ghcVers  = ["8.2.2"]
extentions = []
```
Questions that are still asked by summoner:
- Repository owner:  [willbasky]
- Short project description: 
- Author:  [willbasky]
- Maintainer e-mail:  [email@gmail.com]
- List of categories to choose from: ...
- License: ...
- Add custom prelude? [y]/n
- Supported by 'summoner' GHCs: ...

It is less then without `conf.toml`, but they are.
