### ISSUE TITLE
ensure AppVeyor builds in 64bits

### ISSUE THREAD

**Issue by pascalpoizat** [kowainik/summoner#169]
There is a bug with the builds under Windows, see here:

- https://github.com/simonmar/happy/issues/119
- https://ghc.haskell.org/trac/ghc/ticket/15154

The result is builds in AppVeyor failing with error `-1073741819 `.
It seems that the bug could be solved in a future version of GHC.
Meanwhile, a solution seems to force using 64bits version of stack and have stack build for 64bits too.

The solution corresponds to changing:

```
build: off

before_test:
# http://help.appveyor.com/discussions/problems/6312-curl-command-not-found
- set PATH=C:\Program Files\Git\mingw64\bin;%PATH%

- curl -sS -ostack.zip -L --insecure http://www.stackage.org/stack/windows-i386
- 7z x stack.zip stack.exe

clone_folder: "c:\\stack"
environment:
  global:
    STACK_ROOT: "c:\\sr"

test_script:
- stack setup > nul
# The ugly echo "" hack is to avoid complaints about 0 being an invalid file
# descriptor
- echo "" | stack --no-terminal build --bench --no-run-benchmarks --test
```

into

```
build: off

before_test:
# http://help.appveyor.com/discussions/problems/6312-curl-command-not-found
- set PATH=C:\Program Files\Git\mingw64\bin;%PATH%

- curl -sS -ostack.zip -L --insecure https://www.stackage.org/stack/windows-x86_64
- 7z x stack.zip stack.exe

clone_folder: "c:\\stack"
environment:
  global:
    STACK_ROOT: "c:\\sr"

test_script:
- stack setup > nul
# The ugly echo "" hack is to avoid complaints about 0 being an invalid file
# descriptor
- echo "" | stack --arch x86_64 --no-terminal build --bench --no-run-benchmarks --test
```

in the generated `appveyor.yml`
