### ISSUE TITLE
Add optional 'version' field to the 'prelude`

### ISSUE THREAD

**Issue by chshersh** [kowainik/summoner#411]
So it will look like this:

```toml
[prelude]
    package = "relude"
    module  = "Relude"
    version = "0.6.0.0"
```

And in the `.cabal` file you'll have `relude ^>= 0.6.0.0`

**Open questions**

1. Should we do any validation, like, check that all components are only numbers?
2. What to do with `stack`? Always add to `extra-deps` or just ignore it?

**Alternatives**

Allow arbitrary text in the `version`, so users can write something like:

```haskell
version = ">= 0.6.0.0 && < 0.7
```
