### ISSUE TITLE
Build only `master` branch on AppVeyor

### ISSUE THREAD

**Issue by chshersh** [kowainik/summoner#464]
To speed up CI cycles. We can add the following in `appveyor.yml`

```yaml
# build only master branch
branches:
  only:
    - master
```

What do you think?
